# Note: it's important that none of the packages below depend on ASDF,
# because if they do, the conda version of ASDF will get installed. If that
# happens, then that version will take precendence over the latest developer
# version of ASDF that gets installed just before the documentation build,
# and Sphinx will pick up only the older stable conda package.

name: asdf

dependencies:
  - python>=3
  - sphinx<1.7
  - numpy
  - pyyaml
  - jsonschema>=2.3,<=2.6
  - semantic_version
  - astropy
