# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      NUMPY_VERSION: "stable"
      ASTROPY_VERSION: "stable"
      CONDA_DEPENDENCIES: "semantic_version jsonschema pyyaml six lz4"
      PIP_DEPENDENCIES: "git+http://github.com/spacetelescope/gwcs.git#egg=gwcs"
      PYTHON_ARCH: "64"

  matrix:
      - PYTHON_VERSION: "2.7"
        platform: x64

      - PYTHON_VERSION: "3.5"
        platform: x64

      - PYTHON_VERSION: "3.5"
        ASTROPY_VERSION: "development"
        platform: x64

      - PYTHON_VERSION: "3.6"
        ASTROPY_VERSION: "1.3.2"
        NUMPY_VERSION: "1.12.0"
        platform: x64

      - PYTHON_VERSION: "3.6"
        ASTROPY_VERSION: "1.3.3"
        NUMPY_VERSION: "1.12.0"
        platform: x64

      - PYTHON_VERSION: "3.6"
        platform: x64

      - PYTHON_VERSION: "3.6"
        ASTROPY_VERSION: "development"
        platform: x64

      # Tests against development version of numpy may fail
      - PYTHON_VERSION: "3.6"
        ASTROPY_VERSION: "development"
        NUMPY_VERSION: "development"
        platform: x64

matrix:
  allow_failures:
    - NUMPY_VERSION: "development"

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "git submodule update --init asdf-standard"

# Not a .NET project
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py test"
