# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "3.5.5"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.continuous-integration\\appveyor\\windows_sdk.cmd"

  matrix:
      - PYTHON_VERSION: "2.7"
        NUMPY_VERSION: "1.9.1"
        platform: x86
        PYTHON_ARCH: "32"

      - PYTHON_VERSION: "2.7"
        NUMPY_VERSION: "1.9.1"
        platform: x64
        PYTHON_ARCH: "64"

      - PYTHON_VERSION: "3.4"
        NUMPY_VERSION: "1.9.1"
        platform: x64
        PYTHON_ARCH: "64"

install:
    - "git submodule update --init"

    # Install miniconda using a powershell script.
    - "powershell .continuous-integration/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Install the build and runtime dependencies of the project.
    - "conda update --yes conda"
    # Create a conda environment using the astropy bonus packages
    - "conda create -q --yes -n test -c astropy-ci-extras python=%PYTHON_VERSION%"
    - "activate test"

    # Check that we have the expected version of Python
    - "python --version"

    # Install specified version of numpy and dependencies
    - "conda install -q --yes numpy=%NUMPY_VERSION% pytest Cython jinja2 pyyaml jsonschema psutil six"

    # Install the development version of astropy
    - "%CMD_IN_ENV% pip install git+http://github.com/astropy/astropy.git#egg=astropy"

    - "%CMD_IN_ENV% pip install semver"

# Not a .NET project
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py test"
