# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      SETUP_CMD: "test"
      NUMPY_VERSION: "stable"
      ASTROPY_VERSION: "development"
      #GWCS_GIT: "git+git://github.com/spacetelescope/gwcs.git#egg=gwcs"
      GWCS_GIT: "git+git://github.com/nden/gwcs@move-schemas#egg=gwcs"
      CONDA_DEPENDENCIES: "semantic_version jsonschema pyyaml six lz4"
      PIP_DEPENDENCIES: "pytest-astropy pytest-faulthandler"
      PYTHON_ARCH: "64"

  matrix:
      # Make sure that installation does not fail
      - PYTHON_VERSION: "3.6"
        SETUP_CMD: "install"
        platform: x64

      - PYTHON_VERSION: "3.5"
        platform: x64

      - PYTHON_VERSION: "3.6"
        NUMPY_VERSION: "1.12.0"
        platform: x64

      - PYTHON_VERSION: "3.6"
        platform: x64

      # Tests against development version of numpy may fail
      - PYTHON_VERSION: "3.6"
        NUMPY_VERSION: "development"
        platform: x64

matrix:
  allow_failures:
    - NUMPY_VERSION: "development"

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "%CMD_IN_ENV% python -m pip install --no-deps %GWCS_GIT%"
    - "%CMD_IN_ENV% python setup.py develop --no-deps"

# Not a .NET project
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py %SETUP_CMD%"
