---
name: Label Checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: backport-2.15.x,development
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  set_milestone:
    name: Set milestone
    runs-on: ubuntu-latest
    needs: [check_labels]
    steps:
      - uses: andrefcdias/add-to-milestone@v1.3.0
        if: ${{ contains(github.event.pull_request.labels.*.name, 'backport-2.15.x') }}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: "2.15.0"
      - uses: andrefcdias/add-to-milestone@v1.3.0
        if: ${{ contains(github.event.pull_request.labels.*.name, 'development') && !contains(github.event.pull_request.labels.*.name, 'backport-2.15.x')}}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: "3.0.0"
